language: python
python:
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: vcutrona
  password:
    secure: fatAlD4R3rnwM6xygOYw8bP3RB4mGlxnvDd2Ees/8TmlRqDB3vGtfAdT3DT6FqZHl/31Y9FN0kjS2u9yb7oQ7ucgLc22Afx/IT4bpqoT8OPws8J3eWh3pNPgLLHeIxIG5cnXh2MPIXmSscjlJ4AtzcBkdf8lQ+w6s1ZTeOlsZTLRJcQfMVlb8Qwxxy1tP7DDDhDJmIaZ5IGSHmAZmev+raGdLJXTyuDWzFuj3KCSdCgUgYF5NzS/zIRwpUxxbbp4FpS1LPkcELOwXNvOsYk2mM7b5VwUINDiQQxPx3qdEwgnRyGq42Fltb6Cuja6/xOIyqEEvs6/hvEvSIM7RgMWNfNpO/IUnstCqfvt3p7gfMw4EkI4nVTyvQ6YH4UiowQeVpk1TaNLnnLQp0A2ILCXaQXtOiDUQL/ydSCvJI4UaBo1romKguh/5OHOyXp4Q2K9Yht8sN1a8Y32Ko4grWpEZcml3Qp7lznCEQgQBG/9jpGAIhhSeJDk0I37+fZ7nzF5SPa4xSOst/UDj/T0Tyt0/EXTizulcI6Q2/oq07UgHee6WGbACXeImIMGi4PQ39UboD+HZ7w7RspM9+zUfxABpoROJbMkMY0MQkFbyEz+G+5RzjxFusO7HJ4R9+EUe0AyyMqXtGJEYrsQbbFwfbab5EkqWLBYCU4wzfZrHCOpKyY=
  on:
    tags: true
    repo: vcutrona/elasticpedia
    python: 3.7
