language: python
python:
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: UzD1o+OqbP5++MaAD4xLxPe85qHYhntPIwy5aCVGx3/mQBL+5jyyn5KSi88AeWDo21v0qf7VYbprzuVuCyuUZKMlpB1EVBaZS3Urh+NrFd7ucM+D5aWpHiI3ebRyP/eNk2VlXU/kd3CoQGhrwFd3bSlsj/KR4W9hQMHbRP3ej0BH3CVozRI7fZGqFpg3mgxCC8FvA2fIjimJDx+S5IXOY18hENKlpGsrEUbtmXjr8dyLMGtYQW1/X84a9bsTa8JfpADEpmyIeb9fIhObWNoUKCztK7et6hf1mqj4vrDRx7es+3zzz02QMtgwK1YIr3Kp2NEk1GcftmySkTJyZRlBzoC2x2eBUfD2UFjmEQcvkCzu1GL/jO/Rl1XJ0LmTMVOPc8FW4MI1xvwID4lePov/uIOpOV3HWy1+pYMEh6bmjkWUP305SM4FqsTs4WkkhxdJhFKSuKrEzZgQACxjuWV0CRp/CkKBYVpIRbJm5PZSKunlNetWZ3akCvZhHHpUy2LwI/HArZUw7ZaSknA3A/AI2ykTrqFuAjaYPCes6POXtRPqHkg3A0OwrZa4HgIF0DOcZfPGiEqBYaTwaB2RHsWAcz/oqJZdDdKpT1GzNejGrFf9RYUrtE+S4jzYgsyF/sACipdWd9lqGlw/r5heKljRF1nznbDhBdX/Vb+4HHHvF08=
  on:
    tags: true
    repo: vcutrona/elasticpedia
    python: 3.7
