from enum import Enum


class Fields(Enum):
    URI = "URI"
    SURFACE_FORM_KEYWORD = "SURFACE_FORM_KEYWORD"
    SURFACE_FORM_PREFIX = "SURFACE_FORM_PREFIX"
    REFCOUNT = "REFCOUNT"
    DESCRIPTION = "DESCRIPTION"
    CLASS = "CLASS"
    CATEGORY = "CATEGORY"
    TEMPLATE = "TEMPLATE"
    REDIRECT = "REDIRECT"
